dfferent methods()


In [ ]:
fname="bushra"
lname="khan"
full_name="MY NAME IS "
print(full_name.isupper())

Listing In python


In [ ]:
listing_method:str=["ratan lal","chaman lal","laal singh"]

print(listing_method)

# del listing_method[0]
# print(listing_method)

#last_seen=listing_method.pop(2) 
#print(last_seen)

#listing_method.remove("chaman lal")
#print(listing_method)

listing_method.sort()

print("here is sorted list method",listing_method)

listing_method.reverse()
print("this is reverse method",listing_method)




looping in lists


In [ ]:
listing_method:str=["ratan lal","chaman lal","laal singh"]
print(f"{listing_method}are great names!")


for list in listing_method:
    print(f"{list.capitalize()} is great name \n i want to know more names like you {list}!")


looping in listing

In [ ]:
for value in range(1,10):
    print(value)

dimension=(0,10)
print(dimension[0])
print(dimension[1])

IF Else conditions

In [ ]:
cars:str=["audi","bmw"]
for car in cars:
    if car=="bmw":
        print(car.upper())
    else:
        print("sorry")

if else chain

In [ ]:
age = 15

if age>12:
    print("your age is greater than 12")
elif age<12:
    print("your age is less than 12")



Dictionary


In [ ]:
book={'color':'blue',
      'pages':120,
      }
new_color=book['color']
print(f'book color is {new_color}')

book['author']="Bushra khan"
book['publisher']='gaba publisher'
print(book)
del book['publisher']
print(book)

# assignment

info={
    'fname':'Bushra',
    'lname':'Khan',
    'age':75,
    'location':'karachi'
}
for key,value in info.items():
    print(f"\n key:{key}")
    print(f"values:{value}")


    



loop in dictionary

In [ ]:
fav_lang={
'sarah':'c',
'asad':'java',
'mavia':'typscript',
'zaid':'python'
}
for key,value in fav_lang.items():
    print(f"{key.title()}'s favorite programming language is {value.capitalize()} ")

Dictionary in Dictionary

In [ ]:
use={
'Bushrakhan':{
    'first_name':"BUshra",
    'last_name':'Khan',
    'age':55,
    'gender':'female'
},
'Hirakhan':{
    'first_name':"Hira",
    'last_name':'Khan',
    'age':25,
    'gender':'female'
}
}
for userName,user_info in use.items():
    print(f'this is user name {userName.capitalize()}')
    print(f'this is user info {user_info}')

User Input

In [ ]:
age=input('how old are you?')

age=int(age)
age>=18


Calculator

In [ ]:
user=input('please enter your name!')
print("Hi!",user)
fnum=input('plz enter first number')
fnum=int(fnum)
print(fnum)




Restaurant Seating: Write a program that asks the user how many people 
are in their dinner group. If the answer is more than eight, print a message saying they’ll have to wait for a table. Otherwise, 
, report that their table is ready.

In [ ]:
user =input("hello sir! how many people are in your dinner group?")
user = int(user)
print(user)
if user<8:
    print("we have seat at the corner!")
elif user>=9:
    print("sorry!")

The while Loop in Action


FUNCTIONS!

In [ ]:
def message(mess):
    print(f"hello i am learning {mess}")
message("python")

In [ ]:
def fav_book(book):
    print(f"My favorite book is {book.title()} ")
fav_book("alice in wonderland")

In [ ]:
def info(name,age=55):
    print(f"hello {name.title()} I know you age i.e {age}")
info("Bushra")

LIST IN FUNCTIONS

In [ ]:
def inner():
    print("inner")
    inner()
    def outer():
        print("outer")
        outer()

Tuple


In [ ]:
names : list[str] = ['Sir Zia',"Muhammad Qasim","DR Noman"]
print( names) ##list


for name in names:
    print("welcome sir :",name.title())


tname:tuple=("bushra khan",50,"ali",23)
print(tname)

for row in tname:
    print(row)
    




Complicate Tuple


In [ ]:
data_base:list[tuple[str,str]]=[("Bushra",123),
                                    ("khan",566)
    ]

input_user:str=input("enter User name!")
input_password:str=input("enter password!")
for row in data_base:
        username,password=row

        if input_user==username and input_password==password:
                print("welcome dear user",username)
                break
else:
        print("invalid")

In [ ]:
data_base:list[tuple[str,str]]=[("ushra",123),
                                    ("khan",566)
    ]

input_user:str=input("enter User name!")
input_password:str=input("enter password!")
for row in data_base:
        user ,password=row

        if input_user==user and input_password==password:
                print(f"valid user {user}")
                break
else:
        print("invalid")

SETS (is mai koi index of duplicate element nahi hota)

In [ ]:
set={'a','b','c',1,2,3,5,2,'a'}
print(set)

dir function (value ki sari properties utha kr samny rakh deta hai)

In [ ]:

print(dir())

Lambda function anonymous function hota hai lambda fun k baad colan sy pehly parameter ata hai jis variable mai ye store hota hai us mai ek argument pass hota hai


In [ ]:
#calc=lambda name:name
#print(calc("bushra"))
square=lambda x:x*x
print(square(10))

map and filter
jab hamai ek functionality list k sary items pr apply krni ho!!!

In [ ]:
a=[x for x in range(1,20)]

def new(y):
    return y*10
    
new_list=list(map(new,a))
print(new_list)



In [ ]:
a=[x for x in range(1,20)]

#MAP KI Jg FILTER KO USE KRK SPECIFIC DATA MILTA HAI
    
new_list=list(filter(lambda y:y<5,a))
print(new_list)


In [24]:
a=[x for x in range(1,20)]
b=[x for x in range(21,40)]
print(a)
print(b)

def new(x,y):
    return x,y
new_list=list(map(new,a,b))
print(new_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
[(1, 21), (2, 22), (3, 23), (4, 24), (5, 25), (6, 26), (7, 27), (8, 28), (9, 29), (10, 30), (11, 31), (12, 32), (13, 33), (14, 34), (15, 35), (16, 36), (17, 37), (18, 38), (19, 39)]


Try Except else finally


In [6]:
x=123
try:                           #it will run when code is correct
    print(x)
except:                        #it will run when when code is not correct
    print("error...")
else:                           # when code wirking (when try will work)
    print("code is working...")
finally:                           #it will work all the time
    print("#it will work all the time")

123
code is working...
#it will work all the time


mutable(builtin data type int, float, string,boolean it can be changed!) and immutable(sets,dic,list it cannot be changed! )

In [9]:
#mutable elaxmple mai reasign k baad id change hui
a="bushra"
b=a
b="khan"
print("orignal",a,id(a))
print("refrence",b,id(b))

orignal bushra 2700715501360
refrence khan 2700715494128


In [35]:
#immutable elaxmple mai reasign k baad id mai changes nahi hui
a=["bushra"]
b=a
b.append("khan")
b=["khan"]   ###ab change hojaye ga qk hmnay nai value assign kardi ab wo naya object ban gaya 
print("orignal",a,id(a))
print("refrence",b,id(b))
print(type(a))

orignal ['bushra', 'khan'] 2700715645952
refrence ['khan'] 2700715644672
<class 'list'>


zfill method() ye method zero ki jaga ko fill krta hai agr single digit hai tw zero pehly laga dega 

In [44]:
a="5"
b=a.zfill(2)
print(b)

05


file handling 
open() method sy kaam krta hai 
syntax open(filepath,mode)
mode:r ,a ,x ,w


In [54]:
# data =open("./file.txt","r") #creat connection
# print(data.read())
# print(data.readline())
# print(data.read(2))
# data.close() #close connection



#in case we dont want to close code we use this method

with open("./file.txt","r") as data:
    print(data.read(2))


he


append method in file handling append is usually use to writ something in data


In [56]:
with open("./file.txt","a") as data:
   data.write("\n hello girl!")


   

write method in file handling is usually use to writ something in data mgr porana wala sub kuch remove hojayega!


In [ ]:
with open("./file.txt","w") as data:
   data.write("\n hello girl!")

x method in file handling  is usually use to create new file and write somethng in it!


In [4]:
with open("./file1.txt","x") as data:
   data.write("\n hello girl!")


FileExistsError: [Errno 17] File exists: './file1.txt'

In [9]:
with open("./file1.txt","r") as data:
   print(data.read())
   print(data.tell())



 hello girl!
14


ValueError: I/O operation on closed file.

CLasses are the blue print , structure, template 
here is the simple example of class

In [15]:
class Employe:
  number=120
  pass
p1=Employe()
p2=Employe()
p3=Employe()

p1.name="Bushra khan"
p2.name="mahad khan"
p3.name="maheen khan"


print(p1.number)



120


little advance of class
The __init__() method 2 is a special method 
that Python runs automatically whenever we create a new instance based 
on the employ class
The self parameter is required in the method definition, and 
it must come first, before the other parameters. It must be included in 
the definition because when Python calls this method later (to create an 
instance of employ), the method call will automatically pass the self argumen

In [2]:
class Employe:

 def __init__(self, name, age,salary):
    self.name=name
    self.age=age
    self.salary=salary
    class Language(Employe):
      def show(self,language):
        self.language=language
        print("the default language is python")


p1=Employe("Bushra",50,4500)
print(f"p1 name is {p1.name} \n age is {p1.age} \n salary is {p1.salary} ")
p2=("Ali")

p1 name is Bushra 
 age is 50 
 salary is 4500 


NameError: name 'Language' is not defined

inheritance in classes

NUMPY

In [1]:
pip install numpy


In [7]:
import numpy as np
a=[1,2,3,4,5]
my_arr=np.array(a)
display(my_arr)

display(f"this is size {my_arr.size}")
display(f"this is dimension {my_arr.ndim}")
display(f"this is shape   {my_arr.shape}")
display(f"this is type  {my_arr.dtype}")
display(f"this is item size {my_arr.itemsize}")

array([1, 2, 3, 4, 5])

'this is size 5'

'this is dimension 1'

'this is shape   (5,)'

'this is type  int32'

'this is item size 4'

Looping in numpy (Basically numpy kaam ko asaan karta hai wo python code jis ko sochny mai mushkil hai numpy ussy asan bana ta hai )

In [8]:
import numpy as np
a=[1,2,3,4,5]
my_arr=np.array(a)

test=my_arr*10
test

test1=my_arr[1:4]*20
test1

array([10, 20, 30, 40, 50])

agar np.array mai single element hoga tw wo scalar hoga agr 2 3 elements hongy to vector hoga of array of array  ko matrix kahaingy matrix mai jitny no of aray hn woo rows and usk elements colume hngy

In [19]:
import numpy as np
# my_arr=np.array(100) #(scalar)
# my_arr
# my_arr=np.array([10,20]) #(vector)
#t my_arr
my_arr=np.array([[10,20],[60,82]])   #matrix
display(my_arr.ndim)

2

arrange numpy

In [2]:
import numpy as np

a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape Numpy

In [9]:
import numpy as np
a=np.arange(1,11).reshape(2,5)
a
b=np.reshape(a,(2,5))   #two rows five colums
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

asarray method


In [11]:
import numpy as np

a=[1,2,3,4,5]

arr=np.asarray(a)
arr

array([1, 2, 3, 4, 5])